services:



  web:
    build:
      context: .
      target: development
    env_file:
      - compose-dev.env
    ports:
      - 80
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
